### ISSUE TITLE
Access to cohort ID in the aggregated measurement reports

### ISSUE THREAD

**Issue by captify-mgruau** [jkarlin/floc#30]
Regarding the recent discussions around analytics and optimization use cases, I have a quick question on the availability of cohort IDs in the aggregate reports documented in the [Conversion Measurement API](https://github.com/WICG/conversion-measurement-api) and [Aggregate Reporting API](https://github.com/csharrison/aggregate-reporting-api).

The aggregate reporting API mentions the possibility of requesting data sliced demographically or by market, can you confirm if there is a plan to allow ad networks to access those reports sliced by cohort IDs too? If we consider that cohort ID is the primary signal for behavioural targeting in the future, it seems critical that this information should be available natively (as opposed to having to be passed in the impression metadata for example).

**Comment by michaelkleber** [comment]
That's an interesting idea.  There would be trade-offs from slicing, of course, since the data you can get from the aggregation APIs is statistically noisier when you're aggregating over a smaller population.

My intuition is that it's better to leave this in control of the entity doing the reporting.  I expect people won't want to slice at the individual flocks level — I doubt the optimal trade-off would be 64K maximally-noisy data points.  Rather, an advertiser might to want to group flocks together in ways that are meaningful, e.g. "the 10% of flocks that are most common customers".

**Comment by captify-mgruau** [comment]
Thank you Michael,
The entity doing the reporting in this context would be the browser, so are you saying that I should ask for confirmation directly to the points of contact of the aggregate reporting API pages?

**Comment by michaelkleber** [comment]
Sorry I was unclear.  I think this is better left in control of the the developers using the measurement APIs.

They are in a good position to know how they want to slice their data; if the browser or the API designer does it for them, it is likely to turn out less useful.
